import { asSubscribable } from "../types/Subscribable";
import { EventRegistry } from "./EventRegistry";
import type { KairoEventMap } from "../../minecraft/KairoEventMap";

export class KairoAfterEvents<E extends KairoEventMap> {
    readonly addonActivate;
    readonly blockContainerClosed;
    readonly blockContainerOpened;
    readonly blockExplode;
    readonly buttonPush;
    readonly dataDrivenEntityTrigger;
    readonly effectAdd;
    readonly entityContainerClosed;
    readonly entityContainerOpened;
    readonly entityDie;
    readonly entityHeal;
    readonly entityHealthChanged;
    readonly entityHitBlock;
    readonly entityHitEntity;
    readonly entityHurt;
    readonly entityItemDrop;
    readonly entityItemPickup;
    readonly entityLoad;
    readonly entityRemove;
    readonly entitySpawn;
    readonly entityUpgrade;
    readonly explosion;
    readonly gameRuleChange;
    readonly itemCompleteUse;
    readonly itemReleaseUse;
    readonly itemStartUse;
    readonly itemStartUseOn;
    readonly itemStopUse;
    readonly itemStopUseOn;
    readonly itemUse;
    readonly leverAction;
    readonly pistonActivate;
    readonly playerBreakBlock;
    readonly playerButtonInput;
    readonly playerDimensionChange;
    readonly playerEmote;
    readonly playerGameModeChange;
    readonly playerHotbarSelectedSlotChange;
    readonly playerInputModeChange;
    readonly playerInputPermissionCategoryChange;
    readonly playerInteractWithBlock;
    readonly playerInteractWithEntity;
    readonly playerInventoryItemChange;
    readonly playerJoin;
    readonly playerLeave;
    readonly playerPlaceBlock;
    readonly playerSpawn;
    readonly playerSwingStart;
    readonly pressurePlatePop;
    readonly pressurePlatePush;
    readonly projectileHitBlock;
    readonly projectileHitEntity;
    readonly scriptEventReceive;
    readonly targetBlockHit;
    readonly tripWireTrip;
    readonly weatherChange;

    constructor(private readonly registry: EventRegistry<E>) {
        this.addonActivate                       = asSubscribable(this.registry.getAfter("addonActivate"));
        this.blockContainerClosed                = asSubscribable(this.registry.getAfter("blockContainerClosed"));
        this.blockContainerOpened                = asSubscribable(this.registry.getAfter("blockContainerOpened"));
        this.blockExplode                        = asSubscribable(this.registry.getAfter("blockExplode"));
        this.buttonPush                          = asSubscribable(this.registry.getAfter("buttonPush"));
        this.dataDrivenEntityTrigger             = asSubscribable(this.registry.getAfter("dataDrivenEntityTrigger"));
        this.effectAdd                           = asSubscribable(this.registry.getAfter("effectAdd"));
        this.entityContainerClosed               = asSubscribable(this.registry.getAfter("entityContainerClosed"));
        this.entityContainerOpened               = asSubscribable(this.registry.getAfter("entityContainerOpened"));
        this.entityDie                           = asSubscribable(this.registry.getAfter("entityDie"));
        this.entityHeal                          = asSubscribable(this.registry.getAfter("entityHeal"));
        this.entityHealthChanged                 = asSubscribable(this.registry.getAfter("entityHealthChanged"));
        this.entityHitBlock                      = asSubscribable(this.registry.getAfter("entityHitBlock"));
        this.entityHitEntity                     = asSubscribable(this.registry.getAfter("entityHitEntity"));
        this.entityHurt                          = asSubscribable(this.registry.getAfter("entityHurt"));
        this.entityItemDrop                      = asSubscribable(this.registry.getAfter("entityItemDrop"));
        this.entityItemPickup                    = asSubscribable(this.registry.getAfter("entityItemPickup"));
        this.entityLoad                          = asSubscribable(this.registry.getAfter("entityLoad"));
        this.entityRemove                        = asSubscribable(this.registry.getAfter("entityRemove"));
        this.entitySpawn                         = asSubscribable(this.registry.getAfter("entitySpawn"));
        this.entityUpgrade                       = asSubscribable(this.registry.getAfter("entityUpgrade"));
        this.explosion                           = asSubscribable(this.registry.getAfter("explosion"));
        this.gameRuleChange                      = asSubscribable(this.registry.getAfter("gameRuleChange"));
        this.itemCompleteUse                     = asSubscribable(this.registry.getAfter("itemCompleteUse"));
        this.itemReleaseUse                      = asSubscribable(this.registry.getAfter("itemReleaseUse"));
        this.itemStartUse                        = asSubscribable(this.registry.getAfter("itemStartUse"));
        this.itemStartUseOn                      = asSubscribable(this.registry.getAfter("itemStartUseOn"));
        this.itemStopUse                         = asSubscribable(this.registry.getAfter("itemStopUse"));
        this.itemStopUseOn                       = asSubscribable(this.registry.getAfter("itemStopUseOn"));
        this.itemUse                             = asSubscribable(this.registry.getAfter("itemUse"));
        this.leverAction                         = asSubscribable(this.registry.getAfter("leverAction"));
        this.pistonActivate                      = asSubscribable(this.registry.getAfter("pistonActivate"));
        this.playerBreakBlock                    = asSubscribable(this.registry.getAfter("playerBreakBlock"));
        this.playerButtonInput                   = asSubscribable(this.registry.getAfter("playerButtonInput"));
        this.playerDimensionChange               = asSubscribable(this.registry.getAfter("playerDimensionChange"));
        this.playerEmote                         = asSubscribable(this.registry.getAfter("playerEmote"));
        this.playerGameModeChange                = asSubscribable(this.registry.getAfter("playerGameModeChange"));
        this.playerHotbarSelectedSlotChange      = asSubscribable(this.registry.getAfter("playerHotbarSelectedSlotChange"));
        this.playerInputModeChange               = asSubscribable(this.registry.getAfter("playerInputModeChange"));
        this.playerInputPermissionCategoryChange = asSubscribable(this.registry.getAfter("playerInputPermissionCategoryChange"));
        this.playerInteractWithBlock             = asSubscribable(this.registry.getAfter("playerInteractWithBlock"));
        this.playerInteractWithEntity            = asSubscribable(this.registry.getAfter("playerInteractWithEntity"));
        this.playerInventoryItemChange           = asSubscribable(this.registry.getAfter("playerInventoryItemChange"));
        this.playerJoin                          = asSubscribable(this.registry.getAfter("playerJoin"));
        this.playerLeave                         = asSubscribable(this.registry.getAfter("playerLeave"));
        this.playerPlaceBlock                    = asSubscribable(this.registry.getAfter("playerPlaceBlock"));
        this.playerSpawn                         = asSubscribable(this.registry.getAfter("playerSpawn"));
        this.playerSwingStart                    = asSubscribable(this.registry.getAfter("playerSwingStart"));
        this.pressurePlatePop                    = asSubscribable(this.registry.getAfter("pressurePlatePop"));
        this.pressurePlatePush                   = asSubscribable(this.registry.getAfter("pressurePlatePush"));
        this.projectileHitBlock                  = asSubscribable(this.registry.getAfter("projectileHitBlock"));
        this.projectileHitEntity                 = asSubscribable(this.registry.getAfter("projectileHitEntity"));
        this.scriptEventReceive                  = asSubscribable(this.registry.getAfter("scriptEventReceive"));
        this.targetBlockHit                      = asSubscribable(this.registry.getAfter("targetBlockHit"));
        this.tripWireTrip                        = asSubscribable(this.registry.getAfter("tripWireTrip"));
        this.weatherChange                       = asSubscribable(this.registry.getAfter("weatherChange"));
    }
}
