import { system } from "@minecraft/server";
import type { EventBindingSpec } from "../router/events/types/EventBindingSpec";
import type { KairoEventMap } from "./KairoEventMap";

function bind<T>(
    signal: { subscribe(cb: (ev: T) => void): (ev: T) => void; unsubscribe(cb: (ev: T) => void): void },
    handler: (ev: T) => void,
) {
    const sub = signal.subscribe(handler);
    return { dispose: () => signal.unsubscribe(sub) };
}

export const minecraftEventBinding: EventBindingSpec<KairoEventMap> = {
    after: {
        addonActivate:                       (_w, _h) => ({ dispose: () => {} }),
        blockContainerClosed:                (w, h) => bind(w.afterEvents.blockContainerClosed, h),
        blockContainerOpened:                (w, h) => bind(w.afterEvents.blockContainerOpened, h),
        blockExplode:                        (w, h) => bind(w.afterEvents.blockExplode, h),
        buttonPush:                          (w, h) => bind(w.afterEvents.buttonPush, h),
        dataDrivenEntityTrigger:             (w, h) => bind(w.afterEvents.dataDrivenEntityTrigger, h),
        effectAdd:                           (w, h) => bind(w.afterEvents.effectAdd, h),
        entityContainerClosed:               (w, h) => bind(w.afterEvents.entityContainerClosed, h),
        entityContainerOpened:               (w, h) => bind(w.afterEvents.entityContainerOpened, h),
        entityDie:                           (w, h) => bind(w.afterEvents.entityDie, h),
        entityHeal:                          (w, h) => bind(w.afterEvents.entityHeal, h),
        entityHealthChanged:                 (w, h) => bind(w.afterEvents.entityHealthChanged, h),
        entityHitBlock:                      (w, h) => bind(w.afterEvents.entityHitBlock, h),
        entityHitEntity:                     (w, h) => bind(w.afterEvents.entityHitEntity, h),
        entityHurt:                          (w, h) => bind(w.afterEvents.entityHurt, h),
        entityItemDrop:                      (w, h) => bind(w.afterEvents.entityItemDrop, h),
        entityItemPickup:                    (w, h) => bind(w.afterEvents.entityItemPickup, h),
        entityLoad:                          (w, h) => bind(w.afterEvents.entityLoad, h),
        entityRemove:                        (w, h) => bind(w.afterEvents.entityRemove, h),
        entitySpawn:                         (w, h) => bind(w.afterEvents.entitySpawn, h),
        entityUpgrade:                       (w, h) => bind(w.afterEvents.entityUpgrade, h),
        explosion:                           (w, h) => bind(w.afterEvents.explosion, h),
        gameRuleChange:                      (w, h) => bind(w.afterEvents.gameRuleChange, h),
        itemCompleteUse:                     (w, h) => bind(w.afterEvents.itemCompleteUse, h),
        itemReleaseUse:                      (w, h) => bind(w.afterEvents.itemReleaseUse, h),
        itemStartUse:                        (w, h) => bind(w.afterEvents.itemStartUse, h),
        itemStartUseOn:                      (w, h) => bind(w.afterEvents.itemStartUseOn, h),
        itemStopUse:                         (w, h) => bind(w.afterEvents.itemStopUse, h),
        itemStopUseOn:                       (w, h) => bind(w.afterEvents.itemStopUseOn, h),
        itemUse:                             (w, h) => bind(w.afterEvents.itemUse, h),
        leverAction:                         (w, h) => bind(w.afterEvents.leverAction, h),
        pistonActivate:                      (w, h) => bind(w.afterEvents.pistonActivate, h),
        playerBreakBlock:                    (w, h) => bind(w.afterEvents.playerBreakBlock, h),
        playerButtonInput:                   (w, h) => bind(w.afterEvents.playerButtonInput, h),
        playerDimensionChange:               (w, h) => bind(w.afterEvents.playerDimensionChange, h),
        playerEmote:                         (w, h) => bind(w.afterEvents.playerEmote, h),
        playerGameModeChange:                (w, h) => bind(w.afterEvents.playerGameModeChange, h),
        playerHotbarSelectedSlotChange:      (w, h) => bind(w.afterEvents.playerHotbarSelectedSlotChange, h),
        playerInputModeChange:               (w, h) => bind(w.afterEvents.playerInputModeChange, h),
        playerInputPermissionCategoryChange: (w, h) => bind(w.afterEvents.playerInputPermissionCategoryChange, h),
        playerInteractWithBlock:             (w, h) => bind(w.afterEvents.playerInteractWithBlock, h),
        playerInteractWithEntity:            (w, h) => bind(w.afterEvents.playerInteractWithEntity, h),
        playerInventoryItemChange:           (w, h) => bind(w.afterEvents.playerInventoryItemChange, h),
        playerJoin:                          (w, h) => bind(w.afterEvents.playerJoin, h),
        playerLeave:                         (w, h) => bind(w.afterEvents.playerLeave, h),
        playerPlaceBlock:                    (w, h) => bind(w.afterEvents.playerPlaceBlock, h),
        playerSpawn:                         (w, h) => bind(w.afterEvents.playerSpawn, h),
        playerSwingStart:                    (w, h) => bind(w.afterEvents.playerSwingStart, h),
        pressurePlatePop:                    (w, h) => bind(w.afterEvents.pressurePlatePop, h),
        pressurePlatePush:                   (w, h) => bind(w.afterEvents.pressurePlatePush, h),
        projectileHitBlock:                  (w, h) => bind(w.afterEvents.projectileHitBlock, h),
        projectileHitEntity:                 (w, h) => bind(w.afterEvents.projectileHitEntity, h),
        scriptEventReceive:                  (_w, h) => bind(system.afterEvents.scriptEventReceive, h),
        targetBlockHit:                      (w, h) => bind(w.afterEvents.targetBlockHit, h),
        tripWireTrip:                        (w, h) => bind(w.afterEvents.tripWireTrip, h),
        weatherChange:                       (w, h) => bind(w.afterEvents.weatherChange, h),
    },
    before: {
        addonDeactivate:          (_w, _h) => ({ dispose: () => {} }),
        effectAdd:                (w, h) => bind(w.beforeEvents.effectAdd, h),
        entityHeal:               (w, h) => bind(w.beforeEvents.entityHeal, h),
        entityHurt:               (w, h) => bind(w.beforeEvents.entityHurt, h),
        entityItemPickup:         (w, h) => bind(w.beforeEvents.entityItemPickup, h),
        entityRemove:             (w, h) => bind(w.beforeEvents.entityRemove, h),
        explosion:                (w, h) => bind(w.beforeEvents.explosion, h),
        itemUse:                  (w, h) => bind(w.beforeEvents.itemUse, h),
        playerBreakBlock:         (w, h) => bind(w.beforeEvents.playerBreakBlock, h),
        playerGameModeChange:     (w, h) => bind(w.beforeEvents.playerGameModeChange, h),
        playerInteractWithBlock:  (w, h) => bind(w.beforeEvents.playerInteractWithBlock, h),
        playerInteractWithEntity: (w, h) => bind(w.beforeEvents.playerInteractWithEntity, h),
        playerLeave:              (w, h) => bind(w.beforeEvents.playerLeave, h),
        shutdown:                 (_w, h) => bind(system.beforeEvents.shutdown, h),
        weatherChange:            (w, h) => bind(w.beforeEvents.weatherChange, h),
    },
};
