import { type AddonProperty } from "./AddonPropertyManager";
import { type KairoCommand, type KairoResponse } from "../utils/KairoUtils";
import { KairoAddonProperties } from "../constants/properties";
type ActivateHandler = () => void | Promise<void>;
type DeactivateHandler = () => void | Promise<void>;
type ScriptEventListener = (data: KairoCommand) => void | Promise<void>;
type ScriptEventCommandHandler = (data: KairoCommand) => Promise<void | KairoResponse>;
type TickHandler = () => void | Promise<void>;
type HandlerOptions = {
    priority?: number;
};
type Assignable<T> = T | {
    run: T;
    options?: HandlerOptions;
};
export declare class Kairo {
    private readonly properties;
    private static instance;
    private initialized;
    private readonly addonManager;
    private readonly addonPropertyManager;
    private readonly addonInitializer;
    private static _initHooks;
    private static _deinitHooks;
    private static _commandHandler?;
    private static _seHooks;
    private static _tickHooks;
    private static _tickIntervalId;
    private static _tickEnabled;
    private constructor();
    private static getInstance;
    static init(properties: KairoAddonProperties): void;
    getProperties(): KairoAddonProperties;
    getSelfAddonProperty(): AddonProperty;
    refreshSessionId(): void;
    subscribeReceiverHooks(): void;
    static unsubscribeInitializeHooks(): void;
    static set onActivate(val: Assignable<ActivateHandler>);
    static set onDeactivate(val: Assignable<DeactivateHandler>);
    static set onScriptEvent(val: ScriptEventCommandHandler);
    static set onTick(fn: TickHandler);
    static addActivate(fn: ActivateHandler, opt?: HandlerOptions): void;
    static addDeactivate(fn: DeactivateHandler, opt?: HandlerOptions): void;
    static addScriptEvent(fn: ScriptEventListener, opt?: HandlerOptions): void;
    static addTick(fn: TickHandler, opt?: HandlerOptions): void;
    _scriptEvent(data: KairoCommand): Promise<void | KairoResponse>;
    _activateAddon(): Promise<void>;
    _deactivateAddon(): Promise<void>;
    private static _pushSorted;
    private static _runActivateHooks;
    private static _runDeactivateHooks;
    private static _runScriptEvent;
    private static _runTick;
    private static _enableTick;
    private static _disableTick;
}
export {};
